name: Build KVM Kernel for Redmi Note 10 Pro (sweet)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Kernel Source
        uses: actions/checkout@v4
        with:
          repository: LineageOS/android_kernel_xiaomi_sm6150
          ref: lineage-23.2
          path: kernel

      - name: Checkout AnyKernel3
        uses: actions/checkout@v4
        with:
          repository: osm0sis/AnyKernel3
          ref: master
          path: AnyKernel3

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential bc bison flex libssl-dev libncurses-dev libelf-dev clang lld llvm crossbuild-essential-arm64 zip

      - name: Configure and Build Kernel
        working-directory: ./kernel
        run: |
          export ARCH=arm64
          export SUBARCH=arm64
          export LLVM=1
          export CC=clang
          export CROSS_COMPILE=aarch64-linux-gnu-

          CONFIG_FILE=$(find arch/arm64/configs/ -type f \( -name "*sweet*" -o -name "*sm6150*" \) | head -n 1 | sed 's|arch/arm64/configs/||')
          echo "Bulunan Config: $CONFIG_FILE"
          make LLVM=1 $CONFIG_FILE

          scripts/config --enable CONFIG_VIRTUALIZATION
          scripts/config --enable CONFIG_KVM
          scripts/config --enable CONFIG_KVM_ARM_HOST

          make LLVM=1 olddefconfig
          make LLVM=1 -j$(nproc)

      - name: Package with AnyKernel3
        run: |
          cp kernel/arch/arm64/boot/Image AnyKernel3/
          cd AnyKernel3
          zip -r9 ../KVM-Kernel-Sweet-Flashable.zip *

      - name: Upload Flashable Zip
        uses: actions/upload-artifact@v4
        with:
          name: KVM-Kernel-Sweet-Flashable
          path: KVM-Kernel-Sweet-Flashable.zip
          
